### ISSUE TITLE
Rocket Logo on Website

### ISSUE THREAD

**Issue by teleprom** [ngx-rocket/ngx-rocket.github.io#2]
Hi, i detect the logo is showing badly on the website, i changed some styles and now look better.

![bad_image_1](https://user-images.githubusercontent.com/51827264/59530797-dc253d00-8eba-11e9-9053-fba5c9da0eec.png)

![ok_image_1](https://user-images.githubusercontent.com/51827264/59530806-df202d80-8eba-11e9-93b5-c6cdaf23e19f.png)

![mobile_image_ok](https://user-images.githubusercontent.com/51827264/59530811-e2b3b480-8eba-11e9-838e-b554c2083ca6.png)

Maybe u find this useful ❤️

**Comment by sinedied** [comment]
Strange, I don't see a distorted image with my Chrome on Mac OS, but thanks for the fix as if you have the issue surely some others people see it like you 👍
